package oopsDemo;

import java.util.Scanner;

public class HardwarePurchase extends Hardware {
	public double v;
	

	public double getV() {
		return v;
	}


	public void setV(double v) {
		this.v = v;
	}


	public static void main(String[] args) {
		int ch;
		System.out.println("!!!!!Welcome to Hardware shop!!!!!!!!!!");
		System.out.println("1.CPU");
		System.out.println("2.Monitor");
		System.out.println("3.printer");
		System.out.println("4.speeker");
		System.out.println("5.keyboard");
		System.out.println("Which product you want to purchase???");
		Scanner sc=new Scanner(System.in);
		ch=sc.nextInt();
		HardwarePurchase HP=new HardwarePurchase();
		switch(ch)
		{
		case 1:
		{
		HP.setName("CPU");	
		System.out.println(HP.getName());
		HP.setDesc("A Central Processing Unit (CPU) is the \"brain\" of a computer, responsible for executing instructions from software and controlling other computer components. ");
		System.out.println(HP.getDesc());
		HP.setPrice(20000);
		System.out.println(HP.getPrice());
		System.out.println("How many quantity do you want???");
		HP.setQty(sc.nextInt());
		HP.setV(HP.getPrice()*HP.getQty());
		break;
		}
		case 2:
		{
			HP.setName("Monitor");	
			System.out.println(HP.getName());
			HP.setDesc("A monitor is an output device that displays visual information generated by a computer or other electronic device ");
			System.out.println(HP.getDesc());
			HP.setPrice(20000);
			System.out.println(HP.getPrice());
			System.out.println("How many quantity do you want???");
			HP.setQty(sc.nextInt());
			HP.setV(HP.getPrice()*HP.getQty());
			System.out.println("Total amount you have to pay:"+HP.getV());
			break;
		
		}
		case 3:
		{
			
		}
		case 4:
		{
			
		}
		case 5:
		{
			
		}
		default:
		{
		System.out.println("Sorry the Products are not available");
		break;
		
		}

}
System.out.println("Thank you for purchase!!!visit again...");
}
}
